name: Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # run riscv tests
  cross_compile_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3.2.0
        with:
          submodules: recursive
      - name: setup riscv toolchain
        run: |
          mkdir /opt/riscv
          export PATH=$PATH:/opt/riscv/bin
          wget https://github.com/howjmay/prebuilt-riscv-spike/releases/download/latest/riscv.tar.gz
          sudo tar -xzf riscv.tar.gz -C /opt/

      - name: run tests
        run: |
          export PATH=$PATH:/opt/riscv/bin
          export SIMULATOR_TYPE=qemu
          export ENABLE_TEST_ALL=true
          sh scripts/cross-test.sh

  # for validate test cases only
  check_test_cases:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        cxx_compiler: [g++-12, clang++-14]
    steps:
      - name: checkout code
        uses: actions/checkout@v3.2.0
      - name: install dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y "${{ matrix.cxx_compiler }}" make gcc
      - name: build artifact
        env:
          CXX: ${{ matrix.cxx_compiler }}
          ENABLE_TEST_ALL: "true"
        run: make test

  coding_style:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3.2.0
      - name: style check
        # clang-format version should be set
        run: |
            sudo apt-get install -q -y clang-format
            bash scripts/check-format.sh
        shell: bash
